### ISSUE TITLE
Server Side Form Validation with Firebase Function

### ISSUE THREAD

**Issue by sethburtonhall** [ProjectProtege/protege#257]
## Goal

Set up server side validation in client forms.

## Reason

The app needs to have both client and server side validation to avoid malicious data.

## Definition of Done

- [ ] edit-profile validation
- [ ] post a job

## Resources
https://firebase.google.com/docs/rules/data-validation

**Comment by AlexVCS** [comment]
I'd like to give this a go. It's still available right? Can it be done without having much Firebase experience?

**Comment by sethburtonhall** [comment]
Hey @AlexVCS We would like to handle data validation within Firebase Security Rules. We may be able to use `pages/api` in NextJS or even Firebase Cloud Functions, but security rules seems to be the preferred way with Firebase.

**Comment by sethburtonhall** [comment]
@AlexVCS Still interested and available? Let me know how I can help.

**Comment by AlexVCS** [comment]
Hey Seth, sorry for the delay. I'm still interested and available, not too familiar with Firebase. Maybe we could pair on this?
