### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by sethburtonhall** [ProjectProtege/protege#260]
Protegé has internationalization built in to accept language translations. We would like to work with community members to do initial tests before we start integrating languages. Our hope is that through these tests we will refactor and refine this process to create the best translator experience.

WIP: We are still figuring out how to best maintain translations once they are merged, since new content may be added and existing content may be updated. We are open to suggestions.

Each translation will live in a [global file](https://github.com/drewclem/protege/blob/develop/components/i18n/GlobalTexts.js). `components/i18n/GlobalTexts.js`.

### DOD

- Add your language to [GlobalTexts](https://github.com/drewclem/protege/blob/develop/components/i18n/GlobalTexts.js) as an object 
- translate the `KEY: 'value'` from the existing `en-us` object

example:
```
  'en-us': {
	KEY: 'value'
  },
  'fr': {
	KEY: 'value'
  },
  'de': {
	KEY: 'value'
  }
  'es': {
	KEY: 'value'
  }
```

**Comment by aurelieverrot** [comment]
I will do the French translations.

**Comment by danielcarlman** [comment]
Count me in!

**Comment by sethburtonhall** [comment]
Thanks @aurelieverrot! I merged in your French translations.

@danielcarlman what translations did you have in mind?

**Comment by sethburtonhall** [comment]
This initial test was successful. We are now ready to take other translations.

**Comment by danielcarlman** [comment]
> Thanks @aurelieverrot! I merged in your French translations.
> 
> @danielcarlman what translations did you have in mind?

Brazilian Portuguese

**Comment by crisbnp** [comment]
I can do Indonesian translations.

**Comment by BogDAAAMN** [comment]
Totally into Romanian translation

**Comment by drewclem** [comment]
@crisbnp @BogDAAAMN @danielcarlman 

those would be amazing translations to have!!

**Comment by sethburtonhall** [comment]
Hey friends, thanks so much for you interest in translations. Let me know how I can help. All translations are currently in one file so that is easier and we already have French!!
